### ISSUE TITLE
'Esc' key does not prioritize closing bank/interface

### ISSUE THREAD

**Issue by syggr** [MoreBuchus/buchus-plugins#1]
Hello it's my first time writing here/using github in general  i don't know if it is appropriate to say it here but i've set my chat toggle hotkey to ESC and whenever im in a bank or other interface it will not close because I use both togglechat and 'ESC close interface' features.

**Comment by MoreBuchus** [comment]
> Hello it's my first time writing here/using github in general i don't know if it is appropriate to say it here but i've set my chat toggle hotkey to ESC and whenever im in a bank or other interface it will not close because I use both togglechat and 'ESC close interface' features.

Should be fixed in the latest update. Thanks for bringing it up!
