### ISSUE TITLE
Does not track defence

### ISSUE THREAD

**Issue by Fishy2623** [MoreBuchus/buchus-plugins#13]
Any specs from myself/party members do not appear anywhere on my screen. Not sure how to fix this. Tried uninstalling the plugin, turn on and off, delete the file from RL, uninstall/reinstall RL. Not sure what information to provide either to help.

**Comment by MoreBuchus** [comment]
It should not show you what specs you hit. It should only show an infobox with the defence icon and the current boss defence. Check a couple of things for me:
1.) That you are all in the same party
2.) Special Attack Counter is enabled

The plugin will not calculate the defence if you are not in a party and if special attack counter is off
