### ISSUE TITLE
Party defence tracker

### ISSUE THREAD

**Issue by cj055** [MoreBuchus/buchus-plugins#16]
So my party defence tracker almost never works and happens to bug out anyone elses when i raid with them. the only time i have seen it work is at tekton. Thinking it had something to do with the vulnerability i disable but no change. i have tried all of the obvious solutions like uninstalling and reinstalling and whatnot but to no avail. I have even reinstalled runelite. Its just a quality of life thing but i sure would love for it to work, atleast sometimes

**Comment by MoreBuchus** [comment]
Double check to make sure that Special Attack Counter is enabled for everyone in party.
