### ISSUE TITLE
Better NPC Highlight: Thrall outline not working anymore

### ISSUE THREAD

**Issue by solowanna** [MoreBuchus/buchus-plugins#17]
Since today the thrall outline doesnt work anymore.
Havent changed anything in the settings (except adding 319 to the outline ids, to check if the outline function in general was still working)

See added picture for the settings i use and the proof it isn't working for the thrall.
![thralls](https://github.com/MoreBuchus/buchus-plugins/assets/2229515/38c44bd1-50b8-4640-9683-63cfa068ec69)

**Comment by MoreBuchus** [comment]
I PR'd the fix. Thanks for reporting it!

https://github.com/runelite/plugin-hub/pull/4600

**Comment by Zorrostrian** [comment]
This happened to me too, how do I update the plugin with your fix?
