### ISSUE TITLE
Better NPC Highlight: Ability to customize color for each highlighted NPC

### ISSUE THREAD

**Issue by Z7-z** [MoreBuchus/buchus-plugins#19]
Currently from all the NPC highlighter plugins only the default one in runelite can highlight individual NPCs with different colours, particularly on their moving tile (not their true tile), however you can't access these settings or export them, you have to actually find the NPC in game to change any color, and you can't share the settings. With your plugin there is tons of customisation that include changing the color for each type of highlight, but you can't change the color for each NPC with the same highlight, is there any possibility of this becoming a thing

**Comment by MoreBuchus** [comment]
This eventually will become a feature. I just need to figure out which way I want to implement it.

**Comment by Z7-z** [comment]
> This eventually will become a feature. I just need to figure out which way I want to implement it.

That is something I was also querying, I'm not sure what's best to make it look presentable. An idea I do have that I have no idea how long it would take to develop is to have a submenu underneath each type of highlight (True Tile, Outline, etc) that says "NPCs Highlighted >" you click on that and it opens up all the names of the NPCs you've highlighted and has the hex code of the color associated with that NPC, with the ability to change it there if needed. With the amount of different colors people will use I do think it needs to be hidden away otherwise it will get messy, not sure if this is a plausible approach though might take you a long time

**Comment by SandroVA** [comment]
+1 to this. @MoreBuchus. Maybe implement the UI how Radius markers did it? 

So something like this:
![image](https://github.com/MoreBuchus/buchus-plugins/assets/7264387/ef4f575a-7bdd-4878-a8f4-f99157a1f606)

**Comment by MoreBuchus** [comment]
For now, you can add preset colors to the presets section. If you have more than 0 preset amounts selected, then it'll add them as a right click option. You can also add ":[preset #]" to the end of any npc, and it'll change the color to that preset color

**Comment by Z7-z** [comment]
> For now, you can add preset colors to the presets section. If you have more than 0 preset amounts selected, then it'll add them as a right click option. You can also add ":[preset #]" to the end of any npc, and it'll change the color to that preset color

thank you! this basically ticks the box unless anyone plans on using more than 5 colors, thank us ir
