### ISSUE TITLE
Significant FPS drops 

### ISSUE THREAD

**Issue by MarvinDexx** [MoreBuchus/buchus-plugins#20]
This plugin seems to be causing heavy FPS drops recently. I've been using it for a few months, yet it only started happening as of late. Possibly something with the last update. 

https://github.com/MoreBuchus/buchus-plugins/assets/139405416/c8f8274b-9460-4b52-93e1-5c522a6cdd1c

^ Notice FPS on the top right

**Comment by MoreBuchus** [comment]
Should be fixed with this update
