### ISSUE TITLE
Better NPC Highlight: Defaults to slayer highlight color, even if slayer highlighting is disabled

### ISSUE THREAD

**Issue by AverageToaster** [MoreBuchus/buchus-plugins#21]
Hey, after the most recent update, it seems that now if an NPC is tagged, and you happen to have a task for it, regardless of the color of the tag you've specifically set for them, it will use the color of the Slayer highlighting, even if you have Slayer highlighting disabled. 

Example here: Tagged greater nechs as orange area, and its using the slayer highlight as the color.
![image](https://github.com/MoreBuchus/buchus-plugins/assets/2941418/cac55515-39ce-4fcd-94ff-c1b0fff866ff)

Let me know if there's anything else I can provide for this issue.

**Comment by MoreBuchus** [comment]
Should be fixed in latest update
