### ISSUE TITLE
Toggle to remove shadow from Display Named NPCs

### ISSUE THREAD

**Issue by Z7-z** [MoreBuchus/buchus-plugins#22]
When an NPC gets inputted into the Display Names section the name does indeed appear however it has a shadow background that I think makes it look more difficult to see compared to without a shadow, if there was a toggle or any possibility to remove this I would think it looks much better

**Comment by MoreBuchus** [comment]
Adding this next update

**Comment by Z7-z** [comment]
excellent love you
