### ISSUE TITLE
Respawn Timer bugged

### ISSUE THREAD

**Issue by Z7-z** [MoreBuchus/buchus-plugins#23]
I've been comparing the respawn timer to the one that's in NPC Indicators and this one does not seem to be working. When I switch on the NPC Indicator respawn timer, it identifies the respawn timer after killing a few of the NPC (in this case I just tested it on a Man) but when I flipped plugins and tried it on this plugin it literally does not have a respawn timer. There has been cases where it will randomly appear after killing loads of NPCs but the timer usually bugs out

**Comment by Osamu01** [comment]
Why is this issue closed? I have this issue as well.

**Comment by Z7-z** [comment]
After a few updates to the plugin you can basically flip the NPCs now so the ones you want respawn timers for you put on the vanilla NPC Indicators plugin, and the ones you want all the fancy features on you can also put on this plugin. Also he didn't reply so I just closed it
