### ISSUE TITLE
Can't find the plugin in RL plguinhub

### ISSUE THREAD

**Issue by berserkys** [MoreBuchus/buchus-plugins#3]
Is this plugin only available through your repo on GitHub? Because I can't find it on the RL plugin hub.

**Comment by MoreBuchus** [comment]
> Is this plugin only available through your repo on GitHub? Because I can't find it on the RL plugin hub.

You did not specify which plugin, but Cox Additions and Toggle Chat are both on the hub

**Comment by berserkys** [comment]
Sorry, I meant the Better NPC Highlight

**Comment by MoreBuchus** [comment]
> Sorry, I meant the Better NPC Highlight

That one has not been reviewed yet, so it is not currently on the hub. If they accept the PR, then it will be. I would keep an eye on the development and github channels in the RuneLite discord to see updates on what plugins get accepted/updated

**Comment by berserkys** [comment]
Appreciate it. I thought I saw in the #github text channel on RL disc that it had been added.
