### ISSUE TITLE
Better NPC Highlight plugin Causing slayer task monster names/levels to be pure white

### ISSUE THREAD

**Issue by nomadicvice** [MoreBuchus/buchus-plugins#30]
![image](https://github.com/MoreBuchus/buchus-plugins/assets/122106639/55ffd352-204f-4ffa-b4fb-0ffa62103e08)

Sorry if this is a dumb post and if this is obvious but i've been looking thru the plugin and can't seem to find where this is toggled customized? I turned the plugin off and on and confirmed that it's causing the names to go white, but cannot for the life of me figure out which settings this is linked to as it doesn't seem to be attached to the Slayer subsection. 

Does anybody have insight to this? Thanks!

**Comment by nomadicvice** [comment]
Also to confirm, I have "Slayer Task Highlight" turned off in the subsection. I see that Highlight color causes the same impact to the name/level that I'm experiencing, but they go from white to red when i turn it on (as that's the default)

**Comment by nomadicvice** [comment]
Update: so i see that the Highlight Menu Names option can toggle the white-name/level for slayer creatures on and off; however how is the plugin deciding that in this instance (where all the slayer features are turned off) to change those details on slayer task creatures?

**Comment by MoreBuchus** [comment]
I am fixing this with the next update. Thank you
