### ISSUE TITLE
Display Name no longer working without any highlight?

### ISSUE THREAD

**Issue by iatethedinosaurs** [MoreBuchus/buchus-plugins#34]
I can't seem to get the Display Name working in the newer versions. I've tried uninstalling and reinstalling the plugin from the hub and resetting the option, but nothing seems to get it to display names again. I did notice that in order to get the names to display again, I had to sideload the 1.0.2 version of the plugin and anything after that doesn't seem to show any of the names I have in the Display Name box. I hope it's no me being dumb and missing something obvious. Thank you.

**Comment by iatethedinosaurs** [comment]
Okay so I placed a breakpoint on where it renders the name and I see now that you need to have a highlight enabled for the npc in order to display the name. Previously we were able to display names without having any highlight. Is that not possible any more?

**Comment by iatethedinosaurs** [comment]
Figured out how the presets work and they're a great replacement for what I was trying to accomplish. Thank you for the amazing plugin!

**Comment by drownzz** [comment]
Does this mean we can only show display names with using any of the highlighting options? 
When I only use the display name it shows it in black which is hard to read.
