### ISSUE TITLE
Incorrect Prep Counts in CoX Additions

### ISSUE THREAD

**Issue by Paddy-OSRS** [MoreBuchus/buchus-plugins#35]
I noticed an issue with the total required number (i.e., the number after "/") of elder, twisted, and kodai potions, as well as the number of noxifer herbs that is displayed in the Prep overlay.

For the elder, twisted, and kodai potions, the required number is 3x too high. It looks like the formula for golpar was copied and used instead. The required number should be equal to the number of Overloads configured. If I enter 1 Overload in the Prep options, it shows that I need 3 golpar (correct), 3 elders, 3 twisteds, and 3 kodais. It should be 1 elder, 1 twisted, and 1 kodai.

![image](https://github.com/MoreBuchus/buchus-plugins/assets/144498194/e2709943-fc44-424b-8207-cbbdc4c4e7fe)

For the noxifer herbs, the required number is supposed to equal the sum of Overloads and Extra Nox configured. Instead, the two values are being concatenated as text. For example, if I enter 12 Overloads and 34 Extra Nox, it shows that I need 1234 total noxifer. It looks like it may be caused by the formula not being wrapped in parentheses.

![image](https://github.com/MoreBuchus/buchus-plugins/assets/144498194/09a361f5-4ab3-4a6a-9061-cf9579ea4d3a)

I don't have enough Github experience to know how to (or if I can) attempt to submit a fix for these myself, but I've included an image of what I believe is the offending code.

![image](https://github.com/MoreBuchus/buchus-plugins/assets/144498194/af0f6663-189f-49fe-9eab-790338e4a5ec)

**Comment by MoreBuchus** [comment]
Fixed next update. Thank you for the detailed response! Was very easy to fix because of that
