### ISSUE TITLE
How can we add inline options like such to put specific options on NPC's

### ISSUE THREAD

**Issue by EliJ91** [MoreBuchus/buchus-plugins#39]
![image](https://github.com/MoreBuchus/buchus-plugins/assets/59631669/610244cb-0fb2-43fa-bf98-1d1a88d9727f)

Is it possible to change the color of an individual NPC? I would like to be able to give each of my thralls an outline but different colors for each combat style.

**Comment by MoreBuchus** [comment]
All of the instructions are in the "Instructions" section.
