### ISSUE TITLE
Better NPC Highlight: Remove highlight priority

### ISSUE THREAD

**Issue by cmsu224** [MoreBuchus/buchus-plugins#5]
Since the Overlay Priority is set to HIGH, it does not work with the [Improved Tile Indicators plugin](https://github.com/LeikvollE/tileindicators/tree/master).  It adds the option to draw the highlight below the player or NPC:
Drawn above player/NPC:
![image](https://user-images.githubusercontent.com/14130954/180840779-7dc2ab55-ade0-4113-8f67-b0dea7eb96b8.png)

Drawn below the player/NPC
![image](https://user-images.githubusercontent.com/14130954/180840796-7b0ca65c-121a-4899-a129-79ac2008ec68.png)

If you could remove or add a toggle to `setPriority(OverlayPriority.HIGH);` it should fix the issue.
![image](https://user-images.githubusercontent.com/14130954/180840864-54186907-d5d8-4461-bd4e-38a741335a51.png)

Thanks!

**Comment by MoreBuchus** [comment]
PR'd these changes. Thank you.
