### ISSUE TITLE
Arclight spec reduces defense by 5% of current defense instead of 5% of starting defense

### ISSUE THREAD

**Issue by pelletier2017** [MoreBuchus/buchus-plugins#8]
The arclight should reduce defense by a percentage of starting defense instead of the current defense. You can see this in action by continuously arclight specing and watching the amount of defense lowered drop slower as his defense goes down. It can be verified with monster examine as well.

According to 
https://oldschool.runescape.wiki/w/Arclight

> Weaken will stack additively upon successful hits unlike the dragon warhammer, which stacks multiplicatively. Two successful special attacks thus reduce an opponent's Strength, Attack and Defence by 10%, or 20% if it is a demon.

**Comment by pelletier2017** [comment]
PR to fix https://github.com/MoreBuchus/buchus-plugins/pull/9

**Comment by MoreBuchus** [comment]
Thank you for reminding me of this! Should be fixed in the next [update](https://github.com/MoreBuchus/buchus-plugins/compare/2ab3c4211754a9f51a94cf89b0afe64ab6fe7193...MoreBuchus:7397f071649230da4f92e4779450e6641fbf2f10)
